/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package popups;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Check;
import models.Debug;
import models.Luggage;
import models.LuggageDAO;

/**
 *
 * @author workplz
 */
public class AddLuggage extends javax.swing.JFrame {

    private String label;
    private String color;
    private String shape;
    private String location;
    private String details;
    private int handlerId;
    private String phoneNr;

    /**
     * Creates new form guiPopupDesign
     */
    public AddLuggage(int handlerId) {
        this.handlerId = handlerId;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        shapeLabel = new javax.swing.JLabel();
        storageLocationLabel = new javax.swing.JLabel();
        adDetailsLabel = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        labelTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        shapeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationTextField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTextField = new javax.swing.JTextArea();
        phoneNrLabel = new javax.swing.JLabel();
        phoneNrText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("AddLuggage.title")); // NOI18N

        labelLabel.setText(bundle.getString("AddLuggage.labelLabel.text")); // NOI18N

        colorLabel.setText(bundle.getString("AddLuggage.colorLabel.text")); // NOI18N

        shapeLabel.setText(bundle.getString("AddLuggage.shapeLabel.text")); // NOI18N

        storageLocationLabel.setText(bundle.getString("AddLuggage.storageLocationLabel.text")); // NOI18N

        adDetailsLabel.setText(bundle.getString("AddLuggage.adDetailsLabel.text")); // NOI18N

        Save.setText(bundle.getString("AddLuggage.Save.text")); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        cancel.setText(bundle.getString("AddLuggage.cancel.text")); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        locationTextField.setColumns(20);
        locationTextField.setRows(5);
        jScrollPane1.setViewportView(locationTextField);

        detailsTextField.setColumns(20);
        detailsTextField.setRows(5);
        jScrollPane2.setViewportView(detailsTextField);

        phoneNrLabel.setText(bundle.getString("AddLuggage.phoneNrLabel.text")); // NOI18N

        phoneNrText.setText(bundle.getString("AddLuggage.phoneNrText.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adDetailsLabel)
                    .addComponent(labelLabel)
                    .addComponent(colorLabel)
                    .addComponent(shapeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(phoneNrLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(storageLocationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                                .addComponent(cancel))
                            .addComponent(labelTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shapeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phoneNrText)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLabel)
                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shapeLabel)
                    .addComponent(shapeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNrLabel)
                    .addComponent(phoneNrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storageLocationLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adDetailsLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel)
                    .addComponent(Save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Luggage newLuggage;
        label = Check.cleanLabel(labelTextField.getText());
        color = colorTextField.getText();
        shape = shapeTextField.getText();
        location = locationTextField.getText();
        details = detailsTextField.getText();
        phoneNr = phoneNrText.getText();
        if (Check.verifyLuggage(label, color, shape, location, details, phoneNr)) {
            Debug.println(Check.cleanPhone(phoneNr));
            newLuggage = new Luggage(label, color, shape, location, details, phoneNr);
            saveData(newLuggage);

        } else {
            JOptionPane.showMessageDialog(null,
                    "Your input was invalid. The label, color and phone number can not be empty",
                    "Input error - empty",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_SaveActionPerformed
    private void saveData(Luggage item) {
        LuggageDAO test = new LuggageDAO();
        try {
            test.create(item, handlerId);
        } catch (SQLException ex) {
            Logger.getLogger(AddLuggage.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Save;
    public javax.swing.JLabel adDetailsLabel;
    public javax.swing.JButton cancel;
    public javax.swing.JLabel colorLabel;
    public javax.swing.JTextField colorTextField;
    public javax.swing.JTextArea detailsTextField;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelLabel;
    public javax.swing.JTextField labelTextField;
    public javax.swing.JTextArea locationTextField;
    public javax.swing.JLabel phoneNrLabel;
    public javax.swing.JTextField phoneNrText;
    public javax.swing.JLabel shapeLabel;
    public javax.swing.JTextField shapeTextField;
    public javax.swing.JLabel storageLocationLabel;
    // End of variables declaration//GEN-END:variables
}
