/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package popups;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import models.Case;
import models.CaseDao;
import models.Check;
import models.Debug;
import models.PDFGenerator;

/**
 *
 * @author Jeroen
 */
public class CaseEditDialog extends javax.swing.JFrame {

    private final java.util.ResourceBundle BUNDLE = java.util.ResourceBundle.getBundle("Bundle");
    private final Color red = new Color(163, 0, 15);
    private Case currentCase = null;
    private boolean resolved = false;
    private Date now = new Date();
    private PDFGenerator pdf;
    private int handlerId;

    /**
     * Creates new form PopUpMedewerker
     *
     * @param currentcase
     * @param handlerId
     */
    public CaseEditDialog(Case currentcase, int handlerId) {
        if (!Check.verifyLogin()) {
            Runtime.getRuntime().exit(1);
        } else {
            this.handlerId = handlerId;
            this.currentCase = currentcase;
            this.setUndecorated(true);
            getRootPane().setBorder(BorderFactory.createLineBorder(red));
            initComponents();
            this.setLocationRelativeTo(null);
            setValues();
        }
    }

    public final void setValues() {
        if (currentCase.getResolveDate() != null) {
            resolved = true;
            statusDropDown.setSelectedIndex(1);
        }
        labelTextField.setText(currentCase.getLabel());
        lastNameTextField.setText(currentCase.getSurName());
        nameTextField.setText(currentCase.getName());
        colorTextField.setText(currentCase.getColor());
        shapeTextField.setText(currentCase.getShape());
        rAdressTextField.setText(currentCase.getResidentAddress());
        rPostalCodeField.setText(currentCase.getResidentPostalCode());
        rCityField.setText(currentCase.getResidentCity());
        hAddressTextField.setText(currentCase.getHomeAddress());
        hPostalCodeField.setText(currentCase.getHomePostalCode());
        hCityField.setText(currentCase.getHomeCity());
        jTextArea1.setText(currentCase.getAditionalDetails());
        jTextArea2.setText(currentCase.getStorageLocation());
        emailAdressField.setText(currentCase.getEmailAdress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        shapeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        hAddressLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        rPostalCodeLabel = new javax.swing.JLabel();
        rCityLabel = new javax.swing.JLabel();
        storageLabel = new javax.swing.JLabel();
        addDetailsLabel = new javax.swing.JLabel();
        rHeaderLabel = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        shapeTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        hAddressTextField = new javax.swing.JTextField();
        rAdressTextField = new javax.swing.JTextField();
        rPostalCodeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        statusDropDown = new javax.swing.JComboBox();
        lastNameTextField = new javax.swing.JTextField();
        rCityField = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        rAddressLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        hHeaderLabel = new javax.swing.JLabel();
        hPostalCodeLabel = new javax.swing.JLabel();
        hPostalCodeField = new javax.swing.JTextField();
        hCityField = new javax.swing.JTextField();
        hCityLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        phoneLabel = new javax.swing.JLabel();
        phoneNrField = new javax.swing.JTextField();
        emailAdressLabel = new javax.swing.JLabel();
        emailAdressField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        labelLabel.setText(bundle.getString("CaseEditDialog.labelLabel.text")); // NOI18N

        colorLabel.setText(bundle.getString("CaseEditDialog.colorLabel.text")); // NOI18N

        shapeLabel.setText(bundle.getString("CaseEditDialog.shapeLabel.text")); // NOI18N

        nameLabel.setText(bundle.getString("CaseEditDialog.nameLabel.text")); // NOI18N

        hAddressLabel.setText(bundle.getString("CaseEditDialog.hAddressLabel.text")); // NOI18N

        statusLabel.setText(bundle.getString("CaseEditDialog.statusLabel.text")); // NOI18N

        lastNameLabel.setText(bundle.getString("CaseEditDialog.lastNameLabel.text")); // NOI18N

        rPostalCodeLabel.setText(bundle.getString("CaseEditDialog.rPostalCodeLabel.text")); // NOI18N

        rCityLabel.setText(bundle.getString("CaseEditDialog.rCityLabel.text")); // NOI18N

        storageLabel.setText(bundle.getString("CaseEditDialog.storageLabel.text")); // NOI18N

        addDetailsLabel.setText(bundle.getString("CaseEditDialog.addDetailsLabel.text")); // NOI18N

        rHeaderLabel.setText(bundle.getString("CaseEditDialog.rHeaderLabel.text")); // NOI18N

        labelTextField.setEditable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        statusDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pending", "Resolved" }));

        printButton.setText(bundle.getString("CaseEditDialog.printButton.text")); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        saveButton.setText(bundle.getString("CaseEditDialog.saveButton.text")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("CaseEditDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        rAddressLabel.setText(bundle.getString("CaseEditDialog.rAddressLabel.text")); // NOI18N

        hHeaderLabel.setText(bundle.getString("CaseEditDialog.hHeaderLabel.text")); // NOI18N

        hPostalCodeLabel.setText(bundle.getString("CaseEditDialog.hPostalCodeLabel.text")); // NOI18N

        hCityLabel.setText(bundle.getString("CaseEditDialog.hCityLabel.text")); // NOI18N

        phoneLabel.setText(bundle.getString("CaseEditDialog.phoneLabel.text")); // NOI18N

        phoneNrField.setText(bundle.getString("CaseEditDialog.phoneNrField.text")); // NOI18N

        emailAdressLabel.setText(bundle.getString("CaseEditDialog.emailAdressLabel.text")); // NOI18N

        emailAdressField.setText(bundle.getString("CaseEditDialog.emailAdressField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rHeaderLabel)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rPostalCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDetailsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(printButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rCityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rAdressTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hPostalCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(hPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                                .addComponent(jSeparator2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailAdressLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hHeaderLabel)
                                .addGap(260, 260, 260))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(emailAdressField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shapeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameTextField)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(colorTextField)
                            .addComponent(shapeTextField)
                            .addComponent(phoneNrField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel)
                    .addComponent(labelLabel)
                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(shapeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAdressLabel)
                    .addComponent(emailAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(hHeaderLabel)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hAddressLabel)
                    .addComponent(hAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hPostalCodeLabel)
                    .addComponent(hCityLabel)
                    .addComponent(hCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(rHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rAdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rPostalCodeLabel)
                    .addComponent(rCityLabel)
                    .addComponent(rCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDetailsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String label = Check.cleanAlphaNumeriek(labelTextField.getText());
        String color = Check.cleanAlpha(colorTextField.getText());
        String shape = shapeTextField.getText();
        String surname = Check.cleanAlpha(lastNameTextField.getText());
        String name = Check.cleanAlpha(nameTextField.getText());
        String adres = Check.cleanAlphaNumeriek(hAddressTextField.getText());
        String postalCode = Check.cleanAlphaNumeriek(hPostalCodeField.getText());
        String city = Check.cleanAlpha(hCityField.getText());
        String residentAdres = Check.cleanAlphaNumeriek(rAdressTextField.getText());
        String residentPostalCode = Check.cleanAlphaNumeriek(rPostalCodeField.getText());
        String residentCity = Check.cleanAlpha(rCityField.getText());
        String phoneNr = Check.cleanPhone(phoneNrField.getText());
        String email = emailAdressField.getText();
        String details = jTextArea1.getText();
        String storage = jTextArea2.getText();

        String footer = String.format(BUNDLE.getString("ConfirmFooter"), BUNDLE.getString("Passenger")).toLowerCase();
        String message = BUNDLE.getString("ConfirmHead") + "\n"
                + BUNDLE.getString("AddPassenger.lLabelLabel.text") + " = " + label + "\n"
                + BUNDLE.getString("AddPassenger.colorLabel.text") + " = " + color + "\n"
                + BUNDLE.getString("AddPassenger.shapeLabel.text") + " = " + shape + "\n"
                + BUNDLE.getString("AddPassenger.nameLabel.text") + " = " + name + "\n"
                + BUNDLE.getString("AddPassenger.surNameLabel.text") + " = " + surname + "\n"
                + BUNDLE.getString("AddPassenger.addressHLabel.text") + " = " + adres + "\n"
                + BUNDLE.getString("AddPassenger.postalCodeHLabel.text") + " = " + postalCode + "\n"
                + BUNDLE.getString("AddPassenger.cityHLabel.text") + " = " + city + "\n"
                + BUNDLE.getString("AddPassenger.addressRLabel.text") + " = " + residentAdres + "\n"
                + BUNDLE.getString("AddPassenger.postalCodeRLabel.text") + " = " + residentPostalCode + "\n"
                + BUNDLE.getString("AddPassenger.cityRLabel.text") + " = " + residentCity + "\n"
                + BUNDLE.getString("AddPassenger.phoneNrLabel.text") + " = " + phoneNr + "\n"
                + BUNDLE.getString("AddPassenger.emailAdressLabel.text") + " = " + email + "\n"
                + BUNDLE.getString("PopUpMedewerker.jLabel11.text") + " = " + storage + "\n"
                + BUNDLE.getString("AddPassenger.aditionalDetailsLabel.text") + " = " + details + "\n\n"
                + footer;
        int selectedOption = JOptionPane.showConfirmDialog(null,
                message,
                BUNDLE.getString("Confirm"),
                JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == selectedOption) {
            if (statusDropDown.getSelectedIndex() == 1 && !resolved) {
                currentCase.setResolveDate(now);
            }
            currentCase.setLabel(label);
            currentCase.setSurName(surname);
            currentCase.setName(name);
            currentCase.setColor(color);
            currentCase.setShape(shape);
            currentCase.setHomeAddress(adres);
            currentCase.setHomePostalCode(postalCode);
            currentCase.setHomeCity(city);
            currentCase.setResidentAddress(residentAdres);
            currentCase.setResidentPostalCode(residentPostalCode);
            currentCase.setResidentCity(residentCity);
            currentCase.setAditionalDetails(details);
            currentCase.setPhoneNumber(phoneNr);
            currentCase.setStorageLocation(storage);
            currentCase.setEmailAdress(email);
            Debug.println(currentCase.toString());
            CaseDao dbCase = new CaseDao();
            try {
                dbCase.update(currentCase);
            } catch (SQLException e) {
                Debug.printError(e.toString());
            }
            dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        String label = labelTextField.getText();
        String surname = lastNameTextField.getText();
        String name = nameTextField.getText();
        String color = colorTextField.getText();
        String shape = shapeTextField.getText();
        String residentAdres = rAdressTextField.getText();
        String residentPostalCode = rPostalCodeField.getText();
        String residentCity = rCityField.getText();
        String adres = hAddressTextField.getText();
        String postalCode = hPostalCodeField.getText();
        String city = hCityField.getText();
        String details = jTextArea1.getText();
        String phoneNr = phoneNrField.getText();
        String email = emailAdressField.getText();
        pdf = new PDFGenerator();
        pdf.generate(label, color, shape, name, surname, adres, postalCode, city, residentAdres, residentPostalCode, residentCity, details, handlerId, phoneNr, email);
        pdf.print();
    }//GEN-LAST:event_printButtonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDetailsLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField emailAdressField;
    private javax.swing.JLabel emailAdressLabel;
    private javax.swing.JLabel hAddressLabel;
    private javax.swing.JTextField hAddressTextField;
    private javax.swing.JTextField hCityField;
    private javax.swing.JLabel hCityLabel;
    private javax.swing.JLabel hHeaderLabel;
    private javax.swing.JTextField hPostalCodeField;
    private javax.swing.JLabel hPostalCodeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneNrField;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel rAddressLabel;
    private javax.swing.JTextField rAdressTextField;
    private javax.swing.JTextField rCityField;
    private javax.swing.JLabel rCityLabel;
    private javax.swing.JLabel rHeaderLabel;
    private javax.swing.JTextField rPostalCodeField;
    private javax.swing.JLabel rPostalCodeLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel shapeLabel;
    private javax.swing.JTextField shapeTextField;
    private javax.swing.JComboBox statusDropDown;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel storageLabel;
    // End of variables declaration//GEN-END:variables
}
