package main;

import java.awt.Cursor;
import java.sql.SQLException;
import java.util.List;
import models.Check;
import models.Debug;
import models.User;
import models.UserDAO;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author ChrisvanderHeijden
 */
public class logIn extends javax.swing.JFrame {

    private final java.util.ResourceBundle BUNDLE = java.util.ResourceBundle.getBundle("Bundle");
    private Cursor waitCursor = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);

    /**
     * Creates new form logIn
     */
    public logIn() {
        logIn.super.setCursor(waitCursor);
        Check.resetMedew(null);
        initComponents();
        this.setLocationRelativeTo(null);
        userName.requestFocusInWindow();
        getRootPane().setDefaultButton(LogIn);
        logIn.super.setCursor(defaultCursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        titleLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("login.title")); // NOI18N

        userNameLabel.setText(bundle.getString("logIn.userNameLabel.text")); // NOI18N

        passLabel.setText(bundle.getString("logIn.passLabel.text")); // NOI18N

        LogIn.setText(bundle.getString("logIn.LogIn.text")); // NOI18N
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        titleLabel.setText(bundle.getString("logIn.titleLabel.text")); // NOI18N

        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText(bundle.getString("logIn.errorLabel.text")); // NOI18N
        errorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(titleLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(LogIn)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(errorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(passLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(passWord, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(userNameLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(userName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(titleLabel)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(userNameLabel)
                    .add(userName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passLabel)
                    .add(passWord, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(LogIn)
                .add(18, 18, 18)
                .add(errorLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Log in as soon as the button is pressed
     *
     * @param evt
     */
    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        Cursor waiting = new Cursor(Cursor.WAIT_CURSOR);
        logIn.super.getGlassPane().setCursor(waiting);
        logIn.super.getGlassPane().setVisible(true);
        try {
            String username = userName.getText();
            String password = DigestUtils.sha256Hex(String.valueOf(passWord.getPassword()));

            UserDAO dbMedewerker = new UserDAO();
            List<User> list = null;
            try {
                list = dbMedewerker.readLogIn(username, password);
            } catch (SQLException e) {
                Debug.printError(e.toString());
            }
            if (list.size() == 1) {
                User medew = list.get(0);
                Check.setMedew(medew);
                if (medew.isManager()) {
                    ManagerGui main = new ManagerGui(medew.isAppManager(), medew.getId());
                    main.setVisible(true);
                } else {

                    MainGuiFrame main = new MainGuiFrame(medew.isAppManager(), medew.getId());
                    main.setVisible(true);
                }
                dispose();
            } else {
                errorLabel.setText(BUNDLE.getString("noLogin"));
            }
        } catch (SQLException e) {
            Debug.printError(e.toString());
        }
    }//GEN-LAST:event_LogInActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
